//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_mvc3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentinfo
    {
        public int Student_ID { get; set; }
        public string First_name { get; set; }
        public string Second_name { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public System.DateTime Joining_date { get; set; }
        public Nullable<int> Is_deleted { get; set; }
    }
}
